### ISSUE TITLE
a question about vllm promp building

### ISSUE THREAD

**Issue by Emerald01** [xingyaoww/mint-bench#4]
Hello 
Thank you for your previous answer to help me fix the re-run issues. 
I am actually modifying my own prompt format so it can work better with our custom model template, I just notice that, in the vllm agent, you have the final prompt formatter like this https://github.com/xingyaoww/mint-bench/blob/main/mint/agents/vllm_agent.py#L39
```
       for message in messages:
            if message["role"] == "user":
                prompt += f"\n\nHuman: {message['content']}"
            elif message["role"] == "assistant":
                prompt += f"\n\nAssistant: {message['content']}"
        prompt += "\n\nAssistant:"
```
while in env.step https://github.com/xingyaoww/mint-bench/blob/main/mint/envs/general_env.py#L204
the code is like this:
```
assistant_action = (
                "Assistant:\n" + action.value
                if not action.value.lstrip().startswith("Assistant:")
                else action.value
            )
            self.state.history.append(
                {"role": "assistant", "content": assistant_action + "\n"}
            )
```
It looks to me, the final prompt goes into the model will read like 
```
\n\nAssistant:Assistant\n
```
because `assistant_action` which is the `message["content"]` will append a "\n\nAssistant" while this keyword has already appended when step() function is called?

I am just trying to understand the logic of the code so I may better leverage it with our custom template. I raise this question because I think there might be some sub-optimal here, or maybe I ignore some intermediate procedures.

Thank you.

**Comment by ZihanWang314** [comment]
Hi. 
Short answer: format_prompt is applied to the current state to facilitate generation while env_step is applied to history to help the model understand.
Long answer:
For the format_prompt function, we append "Assistant" at last so the agent will generate content that only contains thoughts and actions, which can be more easily parsed.
For the env.step function, we prepend "Assistant:\n" for the actions the agent generated that do not start with "Assistant:" so every action the agent generate will start with "Assistant:\n" in the history, which is aligned with the in-context example.
Thank you.

**Comment by Emerald01** [comment]
Thank you. Yes, I think I understand the basic workflow here.

The problem I am trying to point out is that, in the following two lines of updates, 

`state: State = env.step(action)`
`action: Action = agent.act(state)`

(a) both will prepend the header "Assistant" if `message["role"] == "assistant"`, then it appears that Assistant will show up twice. 
(b) I am not sure why "Human" is needed in the final prompt, it seems that the few shot example does not include Human anywhere


To confirm this , I print the final prompt that get into the model api, basically print this `prompt`, I note that this prompt is not the final logging prompt but it is indeed the real prompt getting into the model as input https://github.com/xingyaoww/mint-bench/blob/main/mint/agents/vllm_agent.py#L41 

You can see that, there might be two sub-optimals here
1. after the few shot example, the model receives a prompt with header "Assistant: Assistant:"
2. this is another thing that may be not exactly consistent, the header "Human" is actually not in the few-shot instruction, for example, you can see "Human: Observation:", I am not sure this is what we want

I am wondering if you add additional "Assistant" and "Human" for models to reinforce the understanding of the role in that particular sentence, otherwise I thought it might be sub-optimal redundancy and the few-shot example actually does not have this syntax

```
****************** I am printing the prompt ***************************

Human: You are a helpful assistant assigned with the task of problem-solving. To achieve this, you will be using an interactive coding environment equipped with a variety of tool functions to assist you throughout the process.

At each turn, you should first provide your step-by-step thinking for solving the task. Your thought process should be enclosed using "<thought>" tag, for example: <thought> I need to print "Hello World!" </thought>.

After that, you have two options:

1) Interact with a Python programming environment and receive the corresponding output. Your code should be enclosed using "<execute>" tag, for example: <execute> print("Hello World!") </execute>.
2) Directly provide a solution that adheres to the required format for the given task. Your solution should be enclosed using "<solution>" tag, for example: The answer is <solution> A </solution>.

You have 2 chances to interact with the environment or propose a solution. You can only propose a solution 2 times.

Tool function available (already imported in <execute> environment):
[1] wikipedia_search(query: str) -> str
The Wikipedia Search tool provides access to a vast collection of articles covering a wide range of topics.
Can query specific keywords or topics to retrieve accurate and comprehensive information.



---

Task:
Evaluate $\int\int_C (x+y)^2 dx,dy$, where C is the circle defined by $x^2 + y^2 = M$, and M is the birth year of Li Bai.
Output format requirement: Round to three decimal places, using half up rounding rule.

Assistant:
<thought> To solve this problem, let's start by determining Li Bai's birth year. </thought>
<execute> print(wikipedia_search('Li Bai')) </execute>

Observation:
Page: Li Bai
Summary: Li Bai (Chinese: 李白; pinyin: Lǐ Bái, 701–762), also pronounced as Li Bo, courtesy name Taibai (Chinese: 太白), was a Chinese poet, acclaimed from his own time to the present as a brilliant and romantic figure who took traditional poetic forms to new heights.

Assistant:
<thought>
From the wiki_search result, we can see that Li Bai was born in 701, thus M = 701.
To evaluate the double integral of $(x+y)^2$ over the region $C$, where $C$ is the circle defined by $x^2 + y^2 = 701$, we should use polar coordinates.
In polar coordinates, $x = r\cos(\theta)$ and $y = r\sin(\theta)$, and the differential area element $dx,dy$ becomes $r,dr,d\theta$.
$\int\int_C (x+y)^2 dx,dy = \int_0^{2\pi}\int_0^{\sqrt{701}} (r\cos(\theta) + r\sin(\theta))^2r,dr,d\theta$
Let's use the SymPy package to calculate this.
</thought>
<execute>
from sympy import symbols, integrate, cos, sin, pi

r, theta = symbols('r theta')

# the integrand
integrand = (r*cos(theta) + r*sin(theta))**2 * r

# perform the double integration
double_integral = integrate(integrate(integrand, (r, 0, 701 ** 0.5)), (theta, 0, 2*pi))
print(double_integral)
</execute>

Observation:
Out[2]: 245700.5*pi

Assistant:
<thought> Let's round this result to three decimal places using half up rounding rule. </thought>
<execute>
import math
print(round(245700.5*math.pi, 3))
</execute>

Observation:
771890.886

Assistant:
The answer is <solution> 771890.886 </solution>.


---

Task:
Let $a,$ $b,$ and $c$ be distinct complex numbers such that
\begin{align*}
a^3 &= 2a + 5, \\
b^3 &= 2b + 5, \\
c^3 &= 2c + 5.
\end{align*}Find $a^3 + b^3 + c^3.$


Assistant: Assistant:

<thought> Let's first solve for $a^3$, $b^3$, and $c^3$ individually. </thought>
<execute>
from sympy import symbols, Eq, solve

a, b, c = symbols('a b c')

eq1 = Eq(a**3, 2*a + 5)
eq2 = Eq(b**3, 2*b + 5)
eq3 = Eq(c**3, 2*c + 5)

solution = solve((eq1, eq2, eq3), (a, b, c))
print(solution)
</execute>


Human: Observation:
[((-1/2 - sqrt(3)*I/2)*(sqrt(1929)/18 + 5/2)**(1/3) + 2/(3*(-1/2 - sqrt(3)*I/2)*(sqrt(1929)/18 + 5/2)**(1/3)), (-1/2 - sqrt(3)*I/2)*(sqrt(1929)/18 + 5/2)**(1/3) + 2/(3*(-1/2 - sqrt(3)*I/2)*(sqrt(1929)/18 + 5/2)**(1/3)), (-1/2 - sqrt(3)*I/2)*(sqrt(1929)/18 + 5/2)**(1/3) + 2/(3*(-1/2 - sqrt(3)*I/2)*(sqrt(1929)/18 + 5/2)**(1/3))), ((-1/2 - sqrt(3)*I/2)*(sqrt(1929)/18 + 5/2)**(1/3) + 2/(3*(-1/2 - sqrt(3)*I/2)*(sqrt(1929)/18 + 5/2)**(1/3)), (-1/2 - sqrt(3)*I/2)*(sqrt(1929)/18 + 5/2)**(1/3) + 2/(3*(-1/2 - sqrt(3)*I/2)*(sqrt(1929)/18 + 5/2)**(1/3)), 2/(3*(-1/2 + sqrt(3)*I/2)*(sqrt(1929)/18 + 5/2)**(1/3)) + (-1/2 + sqrt(3)*I/2)*(sqrt(1929)/18 + 5/2)**(1/3)), ((-1/2 - sqrt(3)*I/2)*(sqrt(1929)/18 + 5/2)**(1/3) + 2/(3*(-1/2 - sqrt(3)*I/2)*(sqrt(1929)/18 + 5/2)**(1/3)), (-1/2 - sqrt(3)*I/2)*(sqrt(1929)/18 + 5/2)**(1/3) + 2/(3*(-1/2 - sqrt(3)*I/2)*(sqrt(1929)/18 + 5/2)**(1/3)), 2/(3*(sqrt(1929)/18 + 5/2)**(1/3)) + (sqrt(1929)/18 + 5/2)**(1/3)), ((-1/2 - sqrt(3)*I/2)*(sqrt(1929)/18 + 5/2)**(1/3) + 2/(3*(-1/2 - sqrt(3)*I/2)*(sqrt(1929)/18 + 5/2)**(1/3)), 2/(3*(-1/2 + sqrt(3)*I/2)*(sqrt(1929)/18 + 5/2)**(1/3)) + (-1/2 + sqrt(3)*I/2)*(sqrt(1929)/18 + 5/2)**(1/3), (-1/2 - sqrt(3)*I/2)*(sqrt(1929)/18 + 5/2)**(1/3) + 2/(3*(-1/2 - sqrt(3)*I/2)*(sqrt(1929)/18 + 5/2)**(1/3))), ((-1/2 - sqrt(3)*I/2)*(sqrt(1929)/18 + 5/2)**(1/3) + 2/(3*(-1/2 - sqrt(3)*I/2)*(sqrt(1929)/18 + 5/2)**(1/3)), 2/(3*(-1/2 + sqrt(3)*I/2)*(sqrt(1929)/18 + 5/2)**(1/3)) + (-1/2 + sqrt(3)*I/2)*(sqrt(1929)/18 + 5/2)**(1/3), 2/(3*(-1/2 + sqrt(3)*I/2)*(sqrt(1929)/18 + 5/2)**(1/3)) + (-1/2 + sqrt(3)*I/2)*(sqrt(1929)/18 + 5/2)**(1/3)), ((-1/2 - sqrt(3)*I/2)*(sqrt(1929)/18 + 5/2)**(1/3) + 2/(3*(-1/2 - sqrt(3)*I/2)*(sqrt(1929)/18 + 5/2)**(1/3)), 2/(3*(-1/2 + sqrt(3)*I/2)*(sqrt(1929)/18 + 5/2)**(1/3)) + (-1/2 + sqrt(3)*I/2)*(sqrt(1929)/18 + 5/2)**(1/3), 2/(3*(sqrt(1929)/18 + 5/2)**(1/3)) + (sqrt(1929)/18 + 5/2)**(1/3)), ((-1/2 - sqrt(3)*I/2)*(sqrt(1929)/18 + 5/2)**(1/3) + 2/(3*(-1/2 - sqrt(3)*I/2)*(sqrt(1929)/18 + 5/2)**(1/3)),...
[Output Truncated]
You have 1 steps left and 2 chances to propose solution left.
You should take the last step to propose a solution.


Assistant:
****************** End printing the prompt ***************************
```

**Comment by ZihanWang314** [comment]
Thanks for your response, and sorry for causing any confusion! 
You are right that the examples themselves do not have "human" tokens; The "Human" "Assistant" tokens are only added when "chat mode" is False, and I believe this only applies to base models like llama-2-base rather than instruction-tuning models like llama-2-chat. We did this followed by claude api, which required all inputs to be formatted with strings rather than messages with "Human" "Assistant" to label different messages when we conducted this research; we simply applied it to open-source base models. We didn't consider the naming conflict between "Assistant" in model actions and dialogue prompts, since we didn't find a uniform choice to format prompt for dialogues in base models, and it doesn't matter for the models to understand the whole prompt and generate reasonable actions even the naming conflict exists.
You can turn the config to set "chat-mode" to be True and customize your own template to transform between messages and texts if needed. Thanks again for pointing this out!

**Comment by Emerald01** [comment]
Okay, this makes sense. I will then further customize our own template tokens. Thank you for clarifying.
Regards
