### ISSUE TITLE
A bug in `ReasoningTask` success check

### ISSUE THREAD

**Issue by ryanhoangt** [xingyaoww/mint-bench#6]
Hi,

It seems like the code in the `compare_w_digits` method in the `ReasoningTask` class failed to compare results with references that have negative values.
Maybe a quick fix is enough: 
```python
return abs(float(reference) - float(answer)) <= 0.05 * abs(float(reference))
```

<img width="661" alt="Screenshot 2024-05-26 at 12 00 32" src="https://github.com/xingyaoww/mint-bench/assets/79442223/20e33d7d-123e-4de8-8a15-d19b3fa8bcde">

**Comment by ZihanWang314** [comment]
Thanks for the note. The problem is now fixed.
